language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install nose coverage coveralls
    - pip install .
       
script: nosetests --with-coverage --cover-package=sccminutes
after_success: coveralls
        
branches:
    only:
        - master
        - testing
