language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
    
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
    - pip3 install nose coverage coveralls
    - pip3 install .
       
script: nosetests --with-coverage --cover-package=sccminutes
after_success: coveralls
        
branches:
    only:
        - master
        - testing
